### PR TITLE
Enable Linux DLL build

### PR DESCRIPTION
**Pull request by DanRStevens**
Adds support for full DLL build from Linux with Mingw.

Edit: This supports Issue #113.

### CODE REVIEW

**Comment by DanRStevens** [comment]
I've been doing a bit of testing on this and have observed crashes on Linux. Oddly, I managed to solve one crash by enabling optimizations. Now it's crashing at a later place in NetHelper, which seems to be trying to dereference a `nullptr`. I'm investigating the cause.

**Comment by DanRStevens** [comment]
Ok, that's really good to hear. This might be a Linux only bug caused by a Mingw incompatibility. It looks like there is some memory corruption happening on Linux. I'll continue to investigate.

**Comment by DanRStevens** [comment]
It seems the faulty handling of `filesystem::is_directory` under Mingw was causing problems with .vol file loading. I applied the fix we discovered elsewhere, and was able to get things to run.

I still experienced crashes during shutdown, but that was traced to bad code generation linking to the `TApp.ShutDown()` call. It seems it was setting the hidden `this` pointer to an uninitialized value from the stack within the local variable section of the stack frame, rather than reading it as the parameter pushed in the `ECX` register. This lead to a crash in the original code when it tried to access member variables. The problem was very clearly caused by Mingw specific code generation.

I replace the `__thiscall` hack with member function casting. Both are MSVC specific hacks, but I think the later is a bit cleaner. This change affected the section of badly generated code, though unfortunately it's still bad. The chained call now loads the correct ECX, but then offsets it by an uninitialized value. The offset is normally to account for things like multiple inheritance, which isn't used here.

I'm stopping here for now.

Assuming nothing broke on Windows, I may want to merge the current changes. It's a big step up on Linux now that the code compiles with Mingw and runs. It's only when it tries to clean up during shutdown that there is still a problem. That's good enough for many development needs.

**Comment by Brett208** [comment]
I compiled and ran these changes in both debug and release modes. Neither seems to produce any warnings or errors on MSVC. I verified that NetFix and IPDropDown appear to load properly. Everything seems to shut down properly. All tests also passed locally for debug mode.

@DanRStevens, unless you have some specific tests you would like me to perform, I'm happy if you merge.

I read through the commits although most of the material felt beyond my application. Too bad mingw requires a hack when using filesystem. I am glad you will have an easier time contributing with it fully compiling on mingw.

**Comment by DanRStevens** [comment]
Thank you very much for the Windows development support.

**Pull request merged**
