### PR TITLE
Create test project - Cleanup

### PR DESCRIPTION
**Pull request by DanRStevens**
This is a cleanup of PR #51.

This one was a little trickier to get right. I found I had to move the commit to add trailing newlines to files ahead of the commit that ran dos2unix. Failing to do so resulted in merge conflicts and unrecognized renames.

I updated the Visual Studio project settings to add `include` as one of the `AdditionalIncludeDirectories`. That minimizes file changes during the rename, and gets rid of the weird folder in `#include "include/..."`. As the main project file `op2ext.vcxproj` did not already include this, it was a manual text addition from me. @Brett208, you may want to check that Visual Studio accepts it, and that it regenerates the project file with the setting in the same position. **Edit:** I saw some AppVeyor build failures for the Release configuration, which were related to this setting. In the old branch, the Debug configuration had this setting added when source files were moved (not when the include folder was created). There was no corresponding addition to the Release configuration. When I added the setting (when the include folder was created), I didn't notice the pre-existing copy in Debug added in the later commit. It didn't generate a merge conflict due to the moved position. In addition to that, I made a path error on my first attempt. That should explain the Release build failures. It should be cleaned up now.

I updated history to include `makefile` changes for each step along the way. The makefile should be functional at each stage.

### CODE REVIEW

**Comment by Brett208** [comment]
Something is keeping Outpost2DLL from compiling on my local machine. Will need to spend some time troubleshooting.

-Brett

**Comment by Brett208** [comment]
Okay, I just switched some project settings back and forth, cleaned out the build directories again and now its working.

Something stale must have not been deleted that was causing Outpost2DLL not to build. Everything works now. Except that we are passing 0 into strcpy_s which causes a debug assert error on MSVC because it isn't supposed to take strcpy_s. This should probably be merged as a matched pair with PR #46 to keep everything working when running.

**Comment by DanRStevens** [comment]
When the submodule was moved, your local copy won't likely auto update the location of the Outpost2DLL code. You may have had a stray folder around for the old copy, and you likely had an empty folder for the new location. Running `git submodule init` and/or `git submodule update` usually fixes that. I ran into a similar issue recently on Linux after the submodule move.

----

I assume the size 0 thing is a difference between `strcpy` and `strcpy_s`. Hmm, kind of makes the "_s"` version not sound very safe. :wink: 

I'll try to coordinate merging with the other branch.

**Comment by DanRStevens** [comment]
I think I'm gone to close this pull request for now (but keep the branch), while we figure out what to do with the test project. I may try to port select changes that we will need later.

**Comment by DanRStevens** [comment]
I'm going to tentatively re-open this until a decision is made about moving forward. Meanwhile, I've ported the two project file update commits from the closed `copyStringToBuffer` branch (PR https://github.com/OutpostUniverse/op2ext/pull/46). They were effectively changes on top of this branch, but where placed on the other branch that had these changes merged in. I'm collecting them here for now, to keep things in one place.

**Comment by DanRStevens** [comment]
There were a lot of merge commits, and a lot of commit noise. Some of the changes on this branch had already been merged to master. As such, I rebased these changes on master to make it easier to see what is being done here.

**Pull request closed without merging**
